name: docker-tansh
services:
  html:
    build:
      context: html-tansh
      target: development
    networks:
      - client-side
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html-tansh/src:/code/src:/usr/share/nginx/html

  backend:
    build:
      context: backend
      target: production
      dockerfile: Dockerfile.production
    ports:
      - 3000:3000
    networks:
      - client-side
    volumes:
      - ./backend:/go/src/tansh
networks:
  client-side: {}