name: docker-tansh
services:
  html:
    build:
      context: html-tansh
      target: development
    networks:
      - client-side
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html-tansh/src:/code/src:/usr/share/nginx/html

  backend:
    build:
      context: backend
      target: production
      dockerfile: Dockerfile.production
    env_file:
      - .env  
    ports:
      - 3000:3000
    networks:
      - client-side
      - server-side
    volumes:
      - ./backend:/go/src/tansh
    depends_on:
      db:
        condition: service_healthy

  db:
      image: postgres:12-alpine
      restart: always
      env_file:
        - .env
      healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 60s 
      networks:
        - server-side
      ports:
        - 5432:5432
      volumes:
        - db-data:/var/lib/postgresql/data

  migrate:
      image: migrate/migrate
      networks:
        - server-side
      volumes:
          - ./backend/migrations/.:/migrations
      command: ["-path", "/migrations", "-database",  "{{PG_STRING}}", "up"]
      links: 
          - db
      
networks:
  client-side: {}
  server-side: {}

volumes:
  db-data: {}